"""add relation between user & article model

Revision ID: 344525e82ce9
Revises: 795041dd10aa
Create Date: 2023-09-10 00:56:22.155279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '344525e82ce9'
down_revision: Union[str, None] = '795041dd10aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'article', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_column('article', 'author_id')
    # ### end Alembic commands ###
