"""add image field to article table

Revision ID: a195d5ceb7f1
Revises: 137ff9f20280
Create Date: 2023-09-09 11:46:37.141495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a195d5ceb7f1'
down_revision: Union[str, None] = '137ff9f20280'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'image')
    # ### end Alembic commands ###
