"""update relation between user & location table 3

Revision ID: a5b8ac02226f
Revises: a8fa2ca33fcf
Create Date: 2023-09-12 11:14:31.731879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a5b8ac02226f'
down_revision: Union[str, None] = 'a8fa2ca33fcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
