"""add slug field to product table

Revision ID: efbde283566d
Revises: 203299168d47
Create Date: 2023-09-12 13:07:40.004504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'efbde283566d'
down_revision: Union[str, None] = '203299168d47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_index('ix_product_name', table_name='product')
    op.create_index(op.f('ix_product_slug'), 'product', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_slug'), table_name='product')
    op.create_index('ix_product_name', 'product', ['name'], unique=False)
    op.drop_column('product', 'slug')
    # ### end Alembic commands ###
